name: 'Hello World'
description: 'greet someone and record time'
inputs: #input params are stored as env variables 
  who-to-greet: #id of input
    description: 'who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'the time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'